"""
SVG to Python map code generator for letsjam.

Converts Inkscape SVG files to LevelMap subclass Python code.
Can be run as a CLI: python -m letsjam.maps.svg_to_py my_map.svg
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

from .svg_loader import parse_svg, _to_letsjam


def _snap(point: tuple[float, float], nodes_lj: list[tuple[float, float]]) -> int:
    """Return index of nearest node to point."""
    px, py = point
    best_idx = 0
    best_dist = math.inf
    for i, (nx, ny) in enumerate(nodes_lj):
        d = math.hypot(nx - px, ny - py)
        if d < best_dist:
            best_dist = d
            best_idx = i
    return best_idx


def _class_name(stem: str) -> str:
    """Convert filename stem to PascalCase class name."""
    # "my_map" → "MyMap", "simple-map" → "SimpleMap", etc.
    parts = stem.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts if p)


def _format_float(x: float, decimals: int = 2) -> str:
    """Format float, stripping trailing zeros."""
    s = f"{x:.{decimals}f}"
    s = s.rstrip("0").rstrip(".")
    if "." not in s:
        s += ".0"
    return s


def _format_point(pt: tuple[float, float]) -> str:
    """Format (x, y) tuple."""
    x, y = pt
    return f"({_format_float(x)}, {_format_float(y)})"


def generate(
    svg_path: str,
    n_cars: int = 6,
    n_trucks: int = 2,
    seed: int = 0,
    class_name: str | None = None,
    scale: float = 1.0,
) -> str:
    """
    Generate Python LevelMap subclass code from an SVG file.

    Returns the generated Python source code as a string.
    """
    vb, collected = parse_svg(svg_path)

    # Transform all collected nodes to letsjam coords
    nodes_lj: list[tuple[float, float]] = [
        _to_letsjam(sx, sy, vb) for sx, sy in collected.nodes_svg
    ]

    # Apply scale factor to all coordinates
    if scale != 1.0:
        nodes_lj = [(x * scale, y * scale) for x, y in nodes_lj]

    # Build streets by snapping endpoints to nearest nodes
    streets: list[tuple[int, int]] = []
    slow_street_ids: set[int] = set()

    for p1_svg, p2_svg, is_dashed in collected.street_svg:
        lj1 = _to_letsjam(*p1_svg, vb)
        lj2 = _to_letsjam(*p2_svg, vb)
        # Apply scale factor to street endpoints to match scaled nodes
        lj1 = (lj1[0] * scale, lj1[1] * scale)
        lj2 = (lj2[0] * scale, lj2[1] * scale)
        from_idx = _snap(lj1, nodes_lj)
        to_idx = _snap(lj2, nodes_lj)
        if from_idx == to_idx:
            # Skip degenerate self-loop
            continue
        street_id = len(streets)
        streets.append((from_idx, to_idx))
        if is_dashed:
            slow_street_ids.add(street_id)

    # Generate Python code
    svg_name = Path(svg_path).name
    if class_name is None:
        class_name = _class_name(Path(svg_path).stem)

    lines = [
        "# Generated by letsjam svg_to_py from " + svg_name,
        "from __future__ import annotations",
        "",
        "from letsjam.maps.base import LevelMap",
        "",
        "",
        f"class {class_name}(LevelMap):",
        "    def __init__(self, n_cars: int = {}, n_trucks: int = {}, seed: int = {}) -> None:".format(
            n_cars, n_trucks, seed
        ),
        '        w = {}'.format(_format_float(vb.w * scale)),
        "        h = w * 9.0 / 16.0",
        "",
        "        nodes = [",
    ]

    # Add nodes with comments
    for i, (x, y) in enumerate(nodes_lj):
        lines.append(f"            {_format_point((x, y))},  # {i}")

    lines.extend([
        "        ]",
        "        streets = [",
    ])

    # Add streets
    for from_idx, to_idx in streets:
        lines.append(f"            ({from_idx}, {to_idx}),")

    lines.extend([
        "        ]",
        "",
        "        super().__init__(nodes=nodes, streets=streets, width=w, seed=seed)",
    ])

    # Add slow streets
    for sid in sorted(slow_street_ids):
        lines.append(f"        self.add_slow_street({sid})")

    # Add parks (scale coordinates)
    for park_pts in collected.parks:
        scaled_park = [(x * scale, y * scale) for x, y in park_pts]
        pts_str = ", ".join(_format_point(pt) for pt in scaled_park)
        lines.append(f"        self.add_park([{pts_str}])")

    # Add rivers (scale coordinates and width)
    for river_pts, width in collected.rivers:
        scaled_river = [(x * scale, y * scale) for x, y in river_pts]
        pts_str = ", ".join(_format_point(pt) for pt in scaled_river)
        width_str = _format_float(width * scale)
        lines.append(f"        self.add_river([{pts_str}], width={width_str})")

    # Add cars
    lines.append(f"        self.add_cars(n_cars, n_trucks)")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Convert Inkscape SVG to letsjam Python map code"
    )
    parser.add_argument("svg_path", help="Path to SVG file")
    parser.add_argument("--out", help="Output file (default: stdout)")
    parser.add_argument("--class", dest="class_name", help="Class name (default: derived from filename)")
    parser.add_argument("--cars", type=int, default=6, help="Default n_cars (default: 6)")
    parser.add_argument("--trucks", type=int, default=2, help="Default n_trucks (default: 2)")
    parser.add_argument("--seed", type=int, default=0, help="Default seed (default: 0)")
    parser.add_argument("--scale", type=float, default=1.0, help="Scale factor for all coordinates and viewport (default: 1.0)")

    args = parser.parse_args()

    code = generate(args.svg_path, n_cars=args.cars, n_trucks=args.trucks, seed=args.seed, class_name=args.class_name, scale=args.scale)

    if args.out:
        with open(args.out, "w") as f:
            f.write(code)
    else:
        sys.stdout.write(code)


if __name__ == "__main__":
    main()
